apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: library/ubuntu 
        command: ["/bin/sh","-c"]
        args: ["echo hello world"]
      restartPolicy: Never
  backoffLimit: 4


